# Generated by Django 3.0.5 on 2020-04-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Name_of_the_story', models.CharField(max_length=200)),
                ('Date', models.DateField(default='')),
                ('Description_Story', models.TextField(null=True)),
            ],
        ),
    ]
