# Generated by Django 3.0.5 on 2020-04-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20200423_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Image',
            field=models.ImageField(default='', upload_to='story/'),
        ),
    ]
