# Generated by Django 3.0.5 on 2020-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
